# Euler 29
# Aug 26 2018
# How many distinct terms are in the
# sequenced generated by a^b for 2<=(a and b)<=100

l = set()
for a in range(2,101):
    for b in range(2,101):
        l.add(a**b)
print(len(l))